@host=http://localhost:5050

###
GET {{host}}/healthcheck

###

POST {{host}}/signup

{
    "email": "myemail2@gmail.com",
    "password": "mypassword"
}

###

# @name login
POST {{host}}/login

{
    "email": "myemail2@gmail.com",
    "password": "mypassword"
}


###

# @ref login
GET {{host}}/me
Authorization: {{login.token}}

###

# @ref login
POST {{host}}/posts
Authorization: {{login.token}}

{
    "post_content": "This is my first post"
}