@host=http://localhost:5050

###
GET {{host}}/healthcheck

###

POST {{host}}/signup

{
    "email": "myemail2@gmail.com",
    "password": "mypassword"
}

###

# @name login
POST {{host}}/login

{
    "email": "myemail2@gmail.com",
    "password": "mypassword"
}


###

# @ref login
GET {{host}}/me
Authorization: {{login.token}}

###

# @ref login
GET {{host}}/posts?page=1&limit=2
Authorization: {{login.token}}

###

# @ref login
POST {{host}}/posts
Authorization: {{login.token}}

{
    "post_content": "This is my third post"
}

###

# @ref login
GET {{host}}/posts/2lq2JChJiv9xI7yRKfTNT9IM5vI
Authorization: {{login.token}}

###

# @ref login
PUT {{host}}/posts/2lq2JChJiv9xI7yRKfTNT9IM5vI
Authorization: {{login.token}}

{
    "post_content": "This is my first post updated"
}

###

# @ref login
DELETE {{host}}/posts/2lq2JChJiv9xI7yRKfTNT9IM5vI
Authorization: {{login.token}}

###
